import {metrics} from './core.js';
const app=document.querySelector('#app');
app.innerHTML=`<p class="notice">Start with your own data. This is a research notebook, not a live quote feed. Use the same reporting period and units for both companies.</p><form id="research"><div class="grid" id="companies"></div><button>Save & compare</button><button type="button" class="secondary" id="export">Export notebook</button><span id="status" role="status"></span></form><div id="results" class="card scroll" hidden></div>`;
const fields=[['date','As-of date','date'],['period','Reporting period (e.g. TTM to June 2026)','text'],['source','Source URL','url'],['price','Share price (USD)','number'],['eps','Diluted EPS (USD, same period)','number'],['revenue','Revenue (USD billions)','number'],['previousRevenue','Prior comparable revenue (USD billions)','number'],['freeCashFlow','Free cash flow (USD billions)','number']];
for(const [ticker,name,url] of [['NVDA','NVIDIA','https://investor.nvidia.com/'],['GOOGL','Alphabet','https://abc.xyz/investor/']]){
 const card=document.createElement('section');card.className='card';card.innerHTML=`<span class="badge">${ticker}</span><h2>${name}</h2><a href="${url}" target="_blank" rel="noopener">Investor relations ↗</a>`;
 for(const [key,label,type] of fields){const id=ticker+'-'+key;const l=document.createElement('label');l.htmlFor=id;l.textContent=label;const i=document.createElement('input');i.id=id;i.name=id;i.type=type;i.required=true;if(type==='number')i.step='any';card.append(l,i);}
 const l=document.createElement('label');l.htmlFor=ticker+'-thesis';l.textContent='Thesis, catalysts & risks';const t=document.createElement('textarea');t.id=ticker+'-thesis';t.name=t.id;card.append(l,t);document.querySelector('#companies').append(card);
}
const form=document.querySelector('form'),status=document.querySelector('#status');
try{const saved=JSON.parse(localStorage.getItem('equity-lens')||'{}');for(const el of form.elements)if(el.name&&typeof saved[el.name]==='string')el.value=saved[el.name];}catch{status.textContent='Saved notebook unavailable. You can still use and export the tool.';}
function compare(){const data=Object.fromEntries(new FormData(form)),rows=[];for(const ticker of ['NVDA','GOOGL']){const v={};for(const [k,,type] of fields)if(type==='number')v[k]=Number(data[ticker+'-'+k]);rows.push(metrics(v));}
 const results=document.querySelector('#results');results.hidden=false;results.replaceChildren();const h=document.createElement('h2');h.textContent='Side-by-side snapshot';results.append(h);const table=document.createElement('table');const entries=[['Metric','NVDA','GOOGL'],['P/E',...rows.map(r=>r.pe===null?'N/M (nonpositive EPS)':r.pe.toFixed(2)+'×')],['Revenue growth',...rows.map(r=>r.revenueGrowth.toFixed(2)+'%')],['Free cash flow margin',...rows.map(r=>r.fcfMargin===null?'N/M':r.fcfMargin.toFixed(2)+'%')]];entries.forEach((row,n)=>{const tr=table.insertRow();row.forEach(value=>{const c=document.createElement(n?'td':'th');c.textContent=value;tr.append(c);});});results.append(table);const p=document.createElement('p');p.textContent=data['NVDA-period']===data['GOOGL-period']?'Check that both snapshots use consistent accounting definitions.':'Reporting-period labels differ. These results may not be directly comparable.';results.append(p);return data;}
form.addEventListener('submit',e=>{e.preventDefault();try{const data=compare();try{localStorage.setItem('equity-lens',JSON.stringify(data));status.textContent='Saved on this browser.';}catch{status.textContent='Comparison ready. Storage unavailable; export to keep a copy.';}}catch(e){status.textContent=e.message;}});
document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(Object.fromEntries(new FormData(form)),null,2)],{type:'application/json'}));a.download='equity-lens-notebook.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
